config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'
  get 'tutorials' => 'tutorials#index'
  get 'tutorials_2' => 'tutorials#index_2'
  get 'tutorials_3' => 'tutorials#index_3'
  resources :tweets
  resources :humans 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
end

app/controllers/humans_controller.rb
class HumansController < ApplicationController
  
  def index
    @tweet = Tweet.find(1)
  end
  
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  
  def index
  end
  
  def index_2
  end
  
  def index_3
  end
  
  def index_4
  end
  
  def index_5
  end
  
  def index_6
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def index
    @tweets = Tweet.all
  end
  
  def new
    @tweet = Tweet.new
  end
  
  def create
    Tweet.create(text: tweet_params[:text])
  end
  
  def show
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end
  
  
  private
  def tweet_params
    params.require(:tweet).permit(:text)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/humans_helper.rb
module HumansHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/humans/index.html.erb
<%= @tweet.text %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictweet</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
    
  </head>
  <header class=header>
    <ol>
      <ui><%= link_to "天使と悪魔の入り口へ", "/" %></ui>
      <ui><%= link_to "人間世界へ", " /humans" %></ui>
    </ol>
  </header>
  <body class="body">
    
    <%= yield %>
    
  </body>
  
  <footer class=footer>
    
  </footer>

</html>

app/views/tutorials/index.html.erb
<h1>ようこそ天使と悪魔の世界へ</h1>
<P>この世界の説明をしよう…心して聞くのだ…</P>
<p></p>

<p><%= link_to "次へ", 'tutorials_2' %></p>

app/views/tutorials/index_2.html.erb
<P>がはははははは</P>
<P>君たちには、これから天使と悪魔の部屋どちらかに入ってもらう</P>
<p>天使の部屋は楽園を</p>
<P>悪魔の部屋は地獄を</P>
<P>さあ！選べ！！！！</P>


<a href='tutorials_3'>天使の部屋</a>
<a href='#'>悪魔の部屋</a>

app/views/tutorials/index_3.html.erb
<P>あなたはたった今天使になりました！</P>
<P>あなたのお告げを待っている人がいます</P>
<P>是非言って上あげてください。。。</P>

<ui><%= link_to "お告げを言う", new_tweet_path %></ui>

app/views/tweets/create.html.erb
<p>あなたの声はきっと多くの人を救うでしょう</p>

app/views/tweets/destroy.html.erb
<p>削除完了</p>

app/views/tweets/index.html.erb
<main class=main>

<div class="container">
  <div class="box">
    <h1>天使と悪魔</h1>
    <p><%= link_to "starat", 'tutorials' %></p>
  </div>
</div>

<svg version="1.1" xmlns="http://www.w3.org/2000/svg"><path id="wave" d=""/></svg>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.0.1/TweenMax.min.js"></script>
<script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/85188/jquery.wavify.js"></script>
    
    
    <% @tweets.each do |tweet|  %>
    <P><%= tweet.text %></P>
    <% end %>
</main>

app/views/tweets/new.html.erb
<%= form_for @tweet do |f| %>
天使の声:<%= f.text_area :text, cols: 40, rows: 3  %>
<%= f.submit "送信" %>
<% end %>

app/views/tweets/show.html.erb
<P>aaa</P>